EX1:ex1.cpp
	g++ -Wall ex1.cpp -o EX1

TRY:try.cpp
	g++ -Wall try.cpp -o TRY

EXAMPLE1:example1.cpp
	g++ -Wall example1.cpp -o EXAMPLE1

EX2:ex2.cpp
	g++ -Wall ex2.cpp -o EX2

EX3:ex3.cpp
	g++ -Wall ex3.cpp -o EX3

EX4:ex4.cpp
	g++ -Wall ex4.cpp -o EX4

EX5:ex5.cpp
	g++ -Wall ex5.cpp -o EX5

TEST:test.cpp
	g++ -Wall test.cpp -o TEST
