EX2:ex2.cpp
	g++ -Wall ex2.cpp -o EX2

EX3:ex3.cpp
	g++ -Wall ex3.cpp -o EX3

EX3_2:ex3_2.cpp
	g++ -Wall ex3_2.cpp -o EX3_2

EX4:ex4.cpp
	g++ -Wall ex4.cpp -o EX4

EX5:ex5.cpp
	g++ -Wall ex5.cpp -o EX5
